![Imgur](https://i.imgur.com/h4PPC71.png)
#**17-modul. Klassifikatsiya (Classification)**
#17.17. Modul boʻyicha yakuniy amaliy topshiriq

**Bu vazifani bajarish orqali quyidagi koʻnikmalarga ega boʻlasiz:**

✔️ maʼlumotlarni tahlil qilish;  
  ✔️ kategorik maʼlumotlarni kodlash;  
  ✔️ Scikit-learn yordamida ML modellar qurish;  
  ✔️ modellarni baholash va solishtirish;  
  ✔️ vizualizatsiya orqali tushunishni kuchaytirish;  
  ✔️ maʼlumotlarga asoslanib xulosa chiqarish.

# **Vazifa. Mushroom (qoʻziqorin) dataset bilan klassifikatsiya modeli qurish**

**Maʼlumotlar toʻplami:**[ Mushroom Dataset](https://www.kaggle.com/datasets/uciml/mushroom-classification/data)


**Vazifa maqsadi:** klassifikatsiyada **KNN, Decision Tree, Random Forest, Logistic Regression** algoritmlarini oʻrganish.
---

### **Vazifalar**

1. **Maʼlumotlarni yuklash va tozalash**  
   - Datasetni yuklab oling va Pandas yordamida oʻqing.  
   - Kategorik ustunlarni tekshiring, agar kerak boʻlsa, one-hot encoding yoki label encoding qiling.  
   - Null qiymatlar mavjudligini tekshiring va kerak bo‘lsa, tozalang.

2. **Maʼlumotlarni tahlil qilish**  
   - Ustunlarning tarqalishini vizualizatsiya qiling.  
   - Maqsad ustunining balansini tekshiring (nechta zaharli va zaharsiz qo‘ziqorinlar bor).  
   - Har bir xususiyatning maqsad ustuniga ta’sirini tahlil qiling.

3. **Modellarni qurish va taqqoslash**  
   - Ma’lumotlarni **training** va **test** to‘plamlariga ajrating (80/20 yoki 70/30).  
   - Quyidagi klassifikatsiya algoritmlarini qo‘llang va natijalarni solishtiring:
     - **K-Nearest Neighbors (KNN)**
     - **Decision Tree**
     - **Random Forest**
     - **Logistic Regression**
   - Har bir model uchun **Confusion Matrix, Precision, Recall, F1-Score** hisoblang.

4. **Model natijalarini vizualizatsiya qilish**  
   - Har bir model uchun **Confusion Matrix**ʼni chizib chiqing.  
   - Precision, Recall va F1-Score’larni bar grafigi ko‘rinishida solishtiring.

5. **Eng yaxshi modelni tanlash**  
   - Qaysi model eng yaxshi natija berdi?  
   - Qaysi metrikaga ko‘ra tanlov qildingiz?  
   - Modelni yanada yaxshilash uchun qanday qo‘shimcha chora-tadbirlar ko‘rish mumkin?

---

**Mushroom dataset ustunlari va ularning tavsifi**  

1. **class** – qoʻziqorinning turi: zaharli (`p`) yoki zaharsiz (`e`). *Bu target (maqsad) ustun hisoblanadi.*  
2. **cap-shape** – qoʻziqorin shapkasi shakli:  
   - `b`: bell (qo‘ng‘iroq)  
   - `c`: conical (konussimon)  
   - `x`: convex (yumaloq)  
   - `f`: flat (tekis)  
   - `k`: knobbed (dumaloq tugunli)  
   - `s`: sunken (botiq)  

3. **cap-surface** – qoʻziqorin shapkasi yuzasi qanday koʻrinishda:  
   - `f`: fibrous (tolali)  
   - `g`: grooved (egik chiziqli)  
   - `y`: scaly (taroqli)  
   - `s`: smooth (silliq)  

4. **cap-color** – qoʻziqorin shapkasi rangi:  
   - `n`: brown (jigarrang)  
   - `b`: buff (to‘q sariq-jigarrang)  
   - `c`: cinnamon (dolchin rang)  
   - `g`: gray (kulrang)  
   - `r`: green (yashil)  
   - `p`: pink (pushti)  
   - `u`: purple (binafsha)  
   - `e`: red (qizil)  
   - `w`: white (oq)  
   - `y`: yellow (sariq)  

5. **bruises** – qoʻziqorin bosilganda dogʻ qoldiradimi?  
   - `t`: true (ha)  
   - `f`: false (yo‘q)  

6. **odor** – qoʻziqorin hidi:  
   - `a`: almond (bodom)  
   - `l`: anise (anis)  
   - `c`: creosote (kreozot – o‘ziga xos oʻtkir hid)  
   - `y`: fishy (baliq hidi)  
   - `f`: foul (yomon hid)  
   - `m`: musty (mog‘or hidi)  
   - `n`: none (hidsiz)  
   - `p`: pungent (keskin hid)  
   - `s`: spicy (achchiq hid)  

7. **gill-attachment** – qoʻziqorin plastinkalarining shapkaga bogʻlanish turi:  
   - `a`: attached (biriktirilgan)  
   - `d`: descending (pastga tushgan)  
   - `f`: free (erkin)  
   - `n`: notched (egik)  

8. **gill-spacing** – plastinkalar orasidagi masofa:  
   - `c`: close (yaqin)  
   - `w`: crowded (juda zich)  
   - `d`: distant (uzoq)  

9. **gill-size** – plastinkalarning o‘lchami:  
   - `b`: broad (keng)  
   - `n`: narrow (tor)  

10. **gill-color** – plastinkalarning rangi:  
    - `k`: black (qora)  
    - `n`: brown (jigarrang)  
    - `b`: buff (to‘q sariq-jigarrang)  
    - `h`: chocolate (shokolad rang)  
    - `g`: gray (kulrang)  
    - `r`: green (yashil)  
    - `o`: orange (to‘q sariq)  
    - `p`: pink (pushti)  
    - `u`: purple (binafsha)  
    - `e`: red (qizil)  
    - `w`: white (oq)  
    - `y`: yellow (sariq)  

11. **stalk-shape** – qoʻziqorin poyasi shakli:  
    - `e`: enlarging (yuqoriga qarab kengaygan)  
    - `t`: tapering (yuqoriga qarab toraygan)  

12. **stalk-root** – qoʻziqorin poyasining ildiz qismi:  
    - `b`: bulbous (kurtakli)  
    - `c`: club (to‘qmoqsimon)  
    - `u`: cup (chashka shaklida)  
    - `e`: equal (baravar)  
    - `z`: rhizomorphs (ildiz tolalar bilan bog‘langan)  
    - `r`: rooted (ildizlangan)  
    - `?`: nomaʼlum  

13. **stalk-surface-above-ring** – qoʻziqorin poyasining halqadan yuqoridagi yuzasi:  
    - `f`: fibrous (tolali)  
    - `y`: scaly (taroqli)  
    - `k`: silky (ipaksimon)  
    - `s`: smooth (silliq)  

14. **stalk-surface-below-ring** – qoʻziqorin poyasining halqadan pastdagi yuzasi:  
    - `f`: fibrous (tolali)  
    - `y`: scaly (taroqli)  
    - `k`: silky (ipaksimon)  
    - `s`: smooth (silliq)  

15. **stalk-color-above-ring** – halqadan yuqoridagi poya rangi:  
    - `n`: brown (jigarrang)  
    - `b`: buff (to‘q sariq-jigarrang)  
    - `c`: cinnamon (dolchin rang)  
    - `g`: gray (kulrang)  
    - `o`: orange (to‘q sariq)  
    - `p`: pink (pushti)  
    - `e`: red (qizil)  
    - `w`: white (oq)  
    - `y`: yellow (sariq)  

16. **stalk-color-below-ring** – halqadan pastdagi poya rangi:  
    - `n`: brown (jigarrang)  
    - `b`: buff (to‘q sariq-jigarrang)  
    - `c`: cinnamon (dolchin rang)  
    - `g`: gray (kulrang)  
    - `o`: orange (to‘q sariq)  
    - `p`: pink (pushti)  
    - `e`: red (qizil)  
    - `w`: white (oq)  
    - `y`: yellow (sariq)  

17. **veil-type** – qoʻziqorin pardasi turi (barcha qiymatlar `p`, yaʼni **partial** (qisman) boʻlgani uchun foydasiz ustun).  

18. **veil-color** – parda rangi:  
    - `n`: brown (jigarrang)  
    - `o`: orange (to‘q sariq)  
    - `w`: white (oq)  
    - `y`: yellow (sariq)  

19. **ring-number** – poyada nechta halqa bor:  
    - `n`: none (yo‘q)  
    - `o`: one (bitta)  
    - `t`: two (ikkita)  

20. **ring-type** – halqa turi:  
    - `c`: cobwebby (o‘rgimchak to‘ri kabi)  
    - `e`: evanescent (tez yo‘qoladigan)  
    - `f`: flaring (kengaygan)  
    - `l`: large (katta)  
    - `n`: none (yo‘q)  
    - `p`: pendant (osilgan)  
    - `s`: sheathing (o‘rab turuvchi)  
    - `z`: zone (halqa shaklidagi chiziq)  

21. **spore-print-color** – qoʻziqorin sporalarining rangi:  
    - `k`: black (qora)  
    - `n`: brown (jigarrang)  
    - `b`: buff (to‘q sariq-jigarrang)  
    - `h`: chocolate (shokolad rang)  
    - `r`: green (yashil)  
    - `o`: orange (to‘q sariq)  
    - `u`: purple (binafsha)  
    - `w`: white (oq)  
    - `y`: yellow (sariq)  

22. **population** – qoʻziqorinlarning soni:  
    - `a`: abundant (ko‘p)  
    - `c`: clustered (to‘plangan)  
    - `n`: numerous (juda ko‘p)  
    - `s`: scattered (sochilgan)  
    - `v`: several (bir necha)  
    - `y`: solitary (yakka)  

23. **habitat** – qoʻziqorin yashaydigan muhit:  
    - `g`: grasses (o‘tloq)  
    - `l`: leaves (barglar orasida)  
    - `m`: meadows (yaylovlar)  
    - `p`: paths (yo‘l bo‘ylab)  
    - `u`: urban (shahar atrofida)  
    - `w`: waste (tashlandiq joylar)  
    - `d`: woods (o‘rmon)

###*** ESLATMA**. *Ushbu amaliy vazifada siz oʻtmagan mavzulardan ham savollar va vazifalar boʻlishi mumkin! Bu savollarni mustaqil oʻrganishingiz kerak boʻladi. Bunday vazifalar mustaqil izlanish koʻnikmangizni oshirish uchun tayyorlandi!*

In [153]:
import pandas as pd
import numpy as np
import sklearn

url="https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/mushrooms.csv"
df = pd.read_csv(url)
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [154]:
#javobni shu yerda yozing.
df.shape

(8124, 23)

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring    8124 non-null   object
 15  stalk-color-below-ring    8124 non-null   object
 16  veil-type                 8124 non-null   object
 17  veil-color                8124 non-null   object
 18  ring-number               8124 non-null   object
 19  ring-type                 8124 non-null   object
 20  spore-print-color         8124 non-null   object
 21  population                8124 non-null   object
 22  habitat                   8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB

In [156]:
df.describe()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124,...,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124
unique,2,6,4,10,2,9,2,2,2,12,...,4,9,9,1,4,3,5,9,6,7
top,e,x,y,n,f,n,f,c,b,b,...,s,w,w,p,w,o,p,w,v,d
freq,4208,3656,3244,2284,4748,3528,7914,6812,5612,1728,...,4936,4464,4384,8124,7924,7488,3968,2388,4040,3148

In [157]:
df.drop("veil-type", axis=1, inplace=True)

In [158]:
df.duplicated().sum()

np.int64(0)

In [159]:
df["class"] = df["class"].map({"p":1, "e":0})
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,x,s,n,t,p,f,c,n,k,...,s,s,w,w,w,o,p,k,s,u
1,0,x,s,y,t,a,f,c,b,k,...,s,s,w,w,w,o,p,n,n,g
2,0,b,s,w,t,l,f,c,b,n,...,s,s,w,w,w,o,p,n,n,m
3,1,x,y,w,t,p,f,c,n,n,...,s,s,w,w,w,o,p,k,s,u
4,0,x,s,g,f,n,f,w,b,k,...,s,s,w,w,w,o,e,n,a,g

In [160]:
X = df.drop("class", axis=1)
y = df["class"]

Ma'lumotlar orasidagi farq unchalik katta emas ekan.Shunday holatda davom etaveramiz.

In [161]:
print(y.value_counts())

class
0    4208
1    3916
Name: count, dtype: int64

In [162]:
from sklearn.model_selection import StratifiedShuffleSplit
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in sss.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

In [163]:
print(y_train.value_counts())
print(y_test.value_counts())

class
0    3366
1    3133
Name: count, dtype: int64
class
0    842
1    783
Name: count, dtype: int64

In [166]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
X_train_encoded = encoder.fit_transform(X_train)

In [167]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [168]:
knn=KNeighborsClassifier()
dt=DecisionTreeClassifier()
rf=RandomForestClassifier()
lr=LogisticRegression()

In [169]:
knn.fit(X_train_encoded, y_train)

KNeighborsClassifier()

In [170]:
dt.fit(X_train_encoded, y_train)

DecisionTreeClassifier()

In [171]:
rf.fit(X_train_encoded, y_train)

RandomForestClassifier()

In [172]:
lr.fit(X_train_encoded, y_train)

LogisticRegression()

In [173]:
X_test_encoded = one_hot_encoder.transform(X_test)

In [131]:
X_train_encoded.shape

(6499, 116)

In [174]:
X_test_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34125 stored elements and shape (1625, 116)>

In [177]:
y_knn_predicted = knn.predict(X_test_encoded)
y_knn_predicted

array([1, 1, 0, ..., 0, 0, 1])

In [178]:
y_dt = dt.predict(X_test_encoded)
y_dt

array([1, 1, 0, ..., 0, 0, 1])

In [179]:
y_rf = rf.predict(X_test_encoded)
y_rf

array([1, 1, 0, ..., 0, 0, 1])

In [180]:
y_lr = lr.predict(X_test_encoded)
y_lr

array([1, 1, 0, ..., 0, 0, 1])

In [181]:
from sklearn.metrics import jaccard_score
print(jaccard_score(y_test, y_knn_predicted))
print(jaccard_score(y_test, y_dt))
print(jaccard_score(y_test, y_rf))
print(jaccard_score(y_test, y_lr))

1.0
1.0
1.0
0.9987228607918263

In [182]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_knn_predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       842
           1       1.00      1.00      1.00       783

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

In [184]:
print(classification_report(y_test, y_dt))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       842
           1       1.00      1.00      1.00       783

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

In [185]:
print(classification_report(y_test, y_rf))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       842
           1       1.00      1.00      1.00       783

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

In [186]:
print(classification_report(y_test, y_lr))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       842
           1       1.00      1.00      1.00       783

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

Men jaccard_score, precision, recall, f1-score va support metrikalariga ko'ra modellarni tanlab oldim

Bizda KNeighborsClassifier(),DecisionTreeClassifier(),RandomForestClassifier() modellar judayam zo'r ishladi ya'ni test setni o'zida 100 foizli natija ko'rsatdi, LogisticRegression() biroz xatolik berdi, lekin shunda ham aniqlik 99.9 foizni beryabdi.Bundan xulosa qilib aytish mumkinki, hamma model zo'r ishladi va hammasidan foydalanish mumkin.